title: Code for IATI Status
description: Monitoring the status of Code for IATI services.

plugins:
  - jekyll-feed
  - jekyll-redirect-from

feed:
  excerpt_only: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      redirect_to: /

exclude:
  - /venv/
  - /tmpl/
  - CNAME
  - Gemfile
  - Gemfile.lock

redirect_from:
  json: false
